global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'powercalc-downloader'
    static_configs:
      - targets: ['host.docker.internal:3000']
    authorization:
      credentials: 'abc'

remote_write:
  - url: '<url>>'
    basic_auth:
      username: '<user>'
      password: '<pass>'
