name: Generate support model list

on:
  pull_request:
    paths:
      - '.github/scripts/supported_models/**'
  push:
    paths:
      - '**/model.json'
    branches:
      - master
  workflow_dispatch:

jobs:
  format:
    name: Generate list
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install -r ${{ github.workspace }}/.github/scripts/supported_models/requirements.txt
      - name: Pull again
        run: git pull || true
      - name: Generate file
        run: |
          python3 ${{ github.workspace }}/.github/scripts/supported_models/generate_file.py
      - uses: EndBug/add-and-commit@v9
        if: github.ref == 'refs/heads/master'
        with:
          add: 'docs/supported_models.md profile_library/library.json'
          message: 'Update profile library'
      - name: Purge powercalc API memory cache
        run: |
          curl -X GET "https://powercalc.lauwbier.nl/api/cache/flush" -H  "Authorization: Bearer ${{ secrets.POWERCALC_API_KEY }}"
      - name: Purge cloudflare cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_KEY: ${{ secrets.CLOUDFLARE_KEY }}
          PURGE_URLS: '["https://powercalc.lauwbier.nl/api/library"]'
